# Generated by Django 4.2.23 on 2025-07-10 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTopicScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_label', models.CharField(choices=[('社会', '社会'), ('まなび', 'まなび'), ('テクノロジー', 'テクノロジー'), ('カルチャー', 'カルチャー'), ('アウトドア', 'アウトドア'), ('フード', 'フード'), ('旅行おでかけ', '旅行おでかけ'), ('ライフスタイル', 'ライフスタイル'), ('ビジネス', 'ビジネス'), ('読書', '読書'), ('キャリア', 'キャリア'), ('デザイン', 'デザイン'), ('IT', 'IT'), ('経済投資', '経済投資'), ('ネットワーク', 'ネットワーク')], max_length=20, verbose_name='トピックラベル')),
                ('score', models.FloatField(default=0.0, help_text='累積平均スコア', verbose_name='スコア')),
                ('count', models.PositiveIntegerField(default=0, help_text='スコアが更新された回数', verbose_name='更新回数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_scores', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ユーザートピックスコア',
                'verbose_name_plural': 'ユーザートピックスコア',
                'indexes': [models.Index(fields=['user', 'topic_label'], name='accounts_us_user_id_28e138_idx')],
                'unique_together': {('user', 'topic_label')},
            },
        ),
    ]
